'use client'
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { ChainId } from '@thirdweb-dev/react'
const inter = Inter({ subsets: ["latin"] });
import {
  ThirdwebProvider,
  metamaskWallet,
  coinbaseWallet,
  walletConnect,
} from "@thirdweb-dev/react";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    return (
      <ThirdwebProvider
      supportedWallets={[
        metamaskWallet({
          recommended: true,
        }),
        coinbaseWallet(),
        walletConnect(),
      ]}
      activeChain="mumbai"
      clientId="481ab3758e443b6d62632bd7b4de222c"
    >
        <html lang="en">
          <body className={inter.className}>
            
            {children}
          </body>
        </html>
      </ThirdwebProvider>
    );

}
// KlGmecuA9YDrbvEV5v191E1n2tHccHqcvzJcR0Lx3B2wZldFSXusxBtHuTcXFPpsnLHpQdhA2uba038frvRqFw